# numpy end-to-end

In [107]:
import numpy as np
import os

In [7]:
#array(list or tuple)
a = np.array([1,2,3])
b = np.array((1,2,3))
print(a)
print(b)

[1 2 3]
[1 2 3]


In [8]:
b[1] = 20
print(b)

[ 1 20  3]


In [9]:
#2D array
a=np.array([[1,2,3],
          [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
a[1][2]=20
print(a)

[[ 1  2  3]
 [ 4  5 20]]


In [11]:
a[:0]

array([], shape=(0, 3), dtype=int32)

In [12]:
#zeros(row,column)
a=np.zeros([3,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
#ones(row,cloumn)
a = np.ones([2,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#arange(starting value,ending value ,interval)
a = np.arange(10,26,5)
print(a)
#arange(no of elements you need,type of data type)
a=np.arange(24,dtype=float)
print(a.size)
print(a.dtype)
print(a)

[10 15 20 25]
24
float64
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]


In [20]:
#linspace(start value,end value,total no of values)
a = np.linspace(5,6,5)
print(a)

[5.   5.25 5.5  5.75 6.  ]


In [21]:
#full(row,column,value for all elements)
a = np.full((3,4),"f")
print(a)

[['f' 'f' 'f' 'f']
 ['f' 'f' 'f' 'f']
 ['f' 'f' 'f' 'f']]


In [53]:
#random.rand(row,column)
#random.randint(start value,end value,(row,column))
a = np.random.rand(3,4)
b = np.random.randint(3,9,(3,4))
print(a)
print(b)

[[0.72543214 0.77735739 0.72359362 0.81521007]
 [0.71173751 0.12883743 0.21190499 0.06909741]
 [0.15862651 0.73136503 0.76404402 0.42322564]]
[[8 6 6 4]
 [4 4 4 3]
 [4 3 6 5]]


In [21]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [22]:
#array.shape gives (no of row,no of column) in a tuple form
print(a.shape)

(2, 3)


In [23]:
#we can also change the shape
a.shape=(6,1)
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [24]:
#ndim gives dimension of an array
print(a.ndim)

2


In [27]:
#dtype gives the datatype of the array
print(a.dtype)

int32


In [38]:
a = np.array([2,4])

In [40]:
#arithmtic operations
print(np.sum(a))
print(np.subtract(a[1],a[0]))
print(np.multiply(a[0],a[1]))
print(np.divide(a[1],a[0]))

6
2
8
2.0


In [79]:
#axis = 1 is a column wise calculation for sum and sub only
#axis = 0 is a  row wise calculation for sum and sub only

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)
print()
print(np.sum([a,b],axis=1))
print(np.sum([a,b],axis=0))
print(np.multiply(a,b))

[1 2 3]
[4 5 6]

[ 6 15]
[5 7 9]
[ 4 10 18]


In [55]:
#equal(first array , second array)checks column wise
#array_equal(first array,second array)checks whole array
a=np.array([1,2,3,4])
b=np.array([1,3,6,4])
print(np.equal(a,b))
print(np.array_equal(a,b))

[ True False False  True]
False


In [67]:
#aggrigate functions
a = np.array([1,2,3,4,5,6])

print(np.mean(a))
print(np.median(a))
print(np.corrcoef(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.0
1.707825127659933
1
6


In [78]:
#array broadcasting[concept]
#a = 3,3 matrix b = 1,3 and the b is extended to 3,3 matrix with the same element for operation this is known as broadasting  
a = np.array([[1,2,3],[4,5,6],[7,6,5]])
b = np.array([[9,8,7]])
print(a)
print()
print(b)
print()
print(np.sum([a,b]))
print()
print(np.multiply(a,b))

[[1 2 3]
 [4 5 6]
 [7 6 5]]

[[9 8 7]]

[[10 10 10]
 [13 13 13]
 [16 14 12]]

[[ 9 16 21]
 [36 40 42]
 [63 48 35]]


In [83]:
#concatenate(first array,second array)

a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([[0,9,8,7],[6,5,4,3]])

print(np.concatenate([a,b],axis=0))
print()
print(np.concatenate([a,b],axis=1))

[[1 2 3 4]
 [5 6 7 8]
 [0 9 8 7]
 [6 5 4 3]]

[[1 2 3 4 0 9 8 7]
 [5 6 7 8 6 5 4 3]]


In [22]:
#normal stacking by rows and vertical stack
print('a',a)
print('b',b)
print()
print('stack by row',np.stack((a,b),axis=0))
print()
print('vertical',np.vstack([a,b]))
print()
#normal stacking by column and horizontal stacknig
print('stack by column',np.stack((a,b),axis=1))
print()
print('horizontal',np.hstack([a,b]))

a [[1 2 3 4]
 [5 6 7 8]]
b [[0 9 8 7]
 [6 5 4 3]]

stack by row [[[1 2 3 4]
  [5 6 7 8]]

 [[0 9 8 7]
  [6 5 4 3]]]

vertical [[1 2 3 4]
 [5 6 7 8]
 [0 9 8 7]
 [6 5 4 3]]

stack by column [[[1 2 3 4]
  [0 9 8 7]]

 [[5 6 7 8]
  [6 5 4 3]]]

horizontal [[1 2 3 4 0 9 8 7]
 [5 6 7 8 6 5 4 3]]


In [24]:
#ravel(array name) = function that brings every element into 1 row
print(a)
print(a.ravel())


[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [35]:
#fetch elements by interval
a=np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(a)
print()
print(a[1,1:-1:2])

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

[12 14 16 18]


In [38]:
#3d array
a=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


In [43]:
#indexing in 3d array
a[1,1]=[8,9]
a[0,0]=[11,12]
print(a)

[[[11 12]
  [ 3  4]]

 [[ 5  6]
  [ 8  9]]]


In [56]:
#identity(integer) = it gives a square matrix 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
#repeat(array,no of times to be repeated,axis if needed)
a= np.array([[1,2,3],[1,2,3]])
print(np.repeat(a,3,axis=1))

[[1 1 1 2 2 2 3 3 3]
 [1 1 1 2 2 2 3 3 3]]


In [76]:
#simple sum [we need center elements to be 5,6,7,8]

a = np.ones([4,4])
print(a)

a[1:3,1:3]=np.array([[5,6],[7,8]])
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 5. 6. 1.]
 [1. 7. 8. 1.]
 [1. 1. 1. 1.]]


In [85]:
#determinant of a identity matrix is one[linear algebra] only for a square matrix
a = np.identity(4)
np.linalg.det(a)

1.0

In [92]:
#reshape(row,column)
print(a)
print(a.reshape(2,2,2,2))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[[[1. 0.]
   [0. 0.]]

  [[0. 1.]
   [0. 0.]]]


 [[[0. 0.]
   [1. 0.]]

  [[0. 0.]
   [0. 1.]]]]


In [115]:
#bringig fie into numpy 
os.chdir('C:/Users/safia/OneDrive/Desktop')#chdir is change directory from os package 
file = np.genfromtxt('demo.txt',delimiter=',')
file.astype('int32')#changes datatype

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [116]:
print(file.reshape(15,2))

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]
 [11. 12.]
 [13. 14.]
 [15. 16.]
 [17. 18.]
 [19. 20.]
 [21. 22.]
 [23. 24.]
 [25. 26.]
 [27. 28.]
 [29. 30.]]


In [124]:
#print file wit restrictions
file > 15 

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [125]:
file[file > 15].astype('int32')

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [132]:
#checking condition 
print(file.astype('int32'))
np.any(file > 25,axis =0)#if axis is not given check the total file and gives only one ouput
np.all(file >= 21,axis=1)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


array([False, False,  True])